import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  gradient: {
    flex: 1,
    width: '100%',
    padding: width * 0.04,
    paddingTop: height * 0.02,
  },
  titleContainer: {
    borderRadius: 20,
    padding: width * 0.04,
    marginBottom: height * 0.02,
    borderWidth: 2,
    borderColor: 'rgba(139, 69, 255, 0.5)',
    alignItems: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#8B45FF',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.6,
        shadowRadius: 12,
      },
      android: {
        elevation: 12,
      },
    }),
  },
  title: {
    fontSize: width * 0.05,
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
    textShadowColor: 'rgba(139, 69, 255, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
    letterSpacing: 0.5,
  },
  subtitle: {
    fontSize: width * 0.04,
    fontWeight: '600',
    color: '#58CCF7',
    textAlign: 'center',
    marginTop: height * 0.01,
    textShadowColor: 'rgba(88, 204, 247, 0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  phrasesContainer: {
    maxHeight: height * 0.25,
    marginBottom: height * 0.02,
  },
  sectionTitle: {
    fontSize: width * 0.045,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: height * 0.015,
    textShadowColor: 'rgba(139, 69, 255, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  phraseItem: {
    marginBottom: height * 0.025,
    borderRadius: 18,
    ...Platform.select({
      ios: {
        shadowColor: '#8B45FF',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.7,
        shadowRadius: 12,
      },
      android: {
        elevation: 12,
      },
    }),
  },
  phraseGradient: {
  borderRadius: 18,
  minWidth: width * 0.7,
  maxWidth: width * 0.85,
  minHeight: height * 0.07,
  maxHeight: height * 0.09,
  paddingVertical: height * 0.01,
  paddingHorizontal: width * 0.04,
  borderWidth: 2,
  borderColor: 'rgba(139, 69, 255, 0.7)',
  alignItems: 'center',
  justifyContent: 'center',
  },
  phraseText: {
    fontSize: width * 0.038,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  dragHint: {
    fontSize: width * 0.03,
    fontWeight: '500',
    color: '#FFD700',
    textAlign: 'center',
    marginTop: height * 0.005,
    textShadowColor: 'rgba(255, 215, 0, 0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  entitiesContainer: {
    marginTop: height * 0.02,
  },
  entitiesRow: {
  flexDirection: 'column',
  justifyContent: 'flex-start',
  alignItems: 'center',
  gap: height * 0.012,
  marginHorizontal: 0,
  },
  entityDropZone: {
  width: width * 0.85,
  minHeight: height * 0.13,
  maxHeight: height * 0.18,
    borderRadius: 18,
    paddingVertical: height * 0.03,
    paddingHorizontal: width * 0.02,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: height * 0.012,
    ...Platform.select({
      ios: {
        shadowColor: '#8B45FF',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  entityTitle: {
    fontSize: width * 0.04,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: height * 0.01,
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  matchedItemsContainer: {
    width: '100%',
    alignItems: 'center',
  },
  matchedItem: {
    backgroundColor: 'rgba(40, 167, 69, 0.2)',
    borderRadius: 10,
    padding: width * 0.025,
    marginVertical: height * 0.005,
    borderWidth: 1,
    borderColor: 'rgba(40, 167, 69, 0.4)',
    width: '100%',
  },
  matchedText: {
    fontSize: width * 0.03,
    fontWeight: '500',
    color: '#FFFFFF',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: width * 0.85,
    borderRadius: 20,
    padding: width * 0.06,
    alignItems: 'center',
    borderWidth: 3,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    ...Platform.select({
      ios: {
        shadowColor: '#8B45FF',
        shadowOffset: { width: 0, height: 15 },
        shadowOpacity: 0.8,
        shadowRadius: 20,
      },
      android: {
        elevation: 20,
      },
    }),
  },
  modalTitle: {
    fontSize: width * 0.055,
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: height * 0.02,
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  modalText: {
    fontSize: width * 0.04,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
    lineHeight: width * 0.06,
    marginBottom: height * 0.02,
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  modalButton: {
    backgroundColor: '#28A745',
    borderRadius: 25,
    paddingVertical: height * 0.015,
    paddingHorizontal: width * 0.08,
    borderWidth: 2,
    borderColor: 'rgba(40, 167, 69, 0.8)',
    ...Platform.select({
      ios: {
        shadowColor: '#28A745',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.6,
        shadowRadius: 10,
      },
      android: {
        elevation: 10,
      },
    }),
  },
  completionButton: {
    backgroundColor: '#28A745',
    borderRadius: 25,
    paddingVertical: height * 0.018,
    paddingHorizontal: width * 0.1,
    borderWidth: 2,
    borderColor: 'rgba(40, 167, 69, 0.8)',
    ...Platform.select({
      ios: {
        shadowColor: '#28A745',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.8,
        shadowRadius: 15,
      },
      android: {
        elevation: 15,
      },
    }),
  },
  modalButtonText: {
    fontSize: width * 0.045,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
});
