import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
  },
  title: {
    fontSize: width < 400 ? 20 : 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 10,
    paddingHorizontal: 10,
  },
  instruction: {
    fontSize: width < 400 ? 14 : 16,
    color: '#B8B8B8',
    textAlign: 'center',
    marginBottom: 15,
    paddingHorizontal: 10,
    lineHeight: 22,
  },
  hintBox: {
    borderRadius: 15,
    padding: 12,
    marginBottom: 20,
    alignItems: 'center',
  },
  hintText: {
    fontSize: width < 400 ? 12 : 14,
    color: '#FFFFFF',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  itemsContainer: {
    flex: 1,
    paddingVertical: 10,
  },
  stepCard: {
    marginBottom: 12,
    borderRadius: 15,
    overflow: 'hidden',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  completedCard: {
    transform: [{ scale: 1.02 }],
  },
  stepGradient: {
    padding: 16,
    borderRadius: 15,
  },
  stepHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  stepIcon: {
    fontSize: 24,
  },
  stepNumber: {
    fontSize: width < 400 ? 12 : 14,
    fontWeight: 'bold',
    color: '#FFFFFF',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
  },
  stepText: {
    fontSize: width < 400 ? 14 : 16,
    color: '#FFFFFF',
    fontWeight: '500',
    lineHeight: 22,
    marginBottom: 10,
  },
  moveButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
  },
  moveButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  moveButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 20,
    gap: 10,
  },
  checkButton: {
    flex: 1,
    borderRadius: 25,
    overflow: 'hidden',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  resetButton: {
    flex: 1,
    borderRadius: 25,
    overflow: 'hidden',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  buttonGradient: {
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    fontSize: width < 400 ? 14 : 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  attemptsText: {
    fontSize: width < 400 ? 14 : 16,
    color: '#58CCF7',
    textAlign: 'center',
    marginTop: 15,
    fontWeight: '600',
  },
});
