import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: width * 0.05,
    paddingVertical: height * 0.0375,
  },
  title: {
    fontSize: width * 0.05,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: height * 0.019,
  },
  instruction: {
    fontSize: width * 0.04,
    color: '#E0E0E0',
    textAlign: 'center',
    marginBottom: height * 0.0375,
    lineHeight: width * 0.055,
  },
  targetBox: {
    width: width * 0.8,
    height: height * 0.125,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: height * 0.0375,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
  },
  completedTargetBox: {
    borderColor: '#4CAF50',
    shadowColor: '#4CAF50',
  },
  targetLabel: {
    fontSize: width * 0.035,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: height * 0.00625,
  },
  targetContent: {
    fontSize: width * 0.045,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  placeholder: {
    fontSize: width * 0.035,
    color: 'rgba(255, 255, 255, 0.7)',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  dragItemsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: width * 0.0375,
    marginBottom: height * 0.0375,
  },
  dragItem: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 8,
    paddingHorizontal: width * 0.04,
    paddingVertical: height * 0.015,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  draggingItem: {
    opacity: 0.7,
    transform: [{ scale: 1.05 }],
  },
  dragItemText: {
    color: '#FFFFFF',
    fontSize: width * 0.035,
    fontWeight: '500',
    textAlign: 'center',
  },
  continueButton: {
    backgroundColor: '#4CAF50',
    borderRadius: 25,
    paddingHorizontal: width * 0.075,
    paddingVertical: height * 0.019,
    shadowColor: '#4CAF50',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  continueButtonText: {
    color: '#FFFFFF',
    fontSize: width * 0.04,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
