import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: width * 0.05,
    paddingVertical: height * 0.025,
  },
  title: {
    fontSize: width * 0.05,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: height * 0.0125,
  },
  instruction: {
    fontSize: width * 0.035,
    color: '#E0E0E0',
    textAlign: 'center',
    marginBottom: height * 0.025,
    lineHeight: width * 0.045,
    paddingHorizontal: width * 0.025,
  },
  meterContainer: {
    width: width * 0.85,
    height: height * 0.15,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: height * 0.025,
    borderWidth: 3,
    borderColor: '#34495E',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  meterLabel: {
    fontSize: width * 0.03,
    fontWeight: '600',
    color: '#BDC3C7',
    marginBottom: height * 0.00625,
  },
  meterDigitsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: width * 0.02,
  },
  meterDigitContainer: {
    width: width * 0.1,
    height: height * 0.0625,
    backgroundColor: '#1C2833',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#34495E',
  },
  meterDigit: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  meterDigitText: {
    fontSize: width * 0.06,
    fontWeight: 'bold',
    color: '#00FF41',
    fontFamily: 'monospace',
  },
  inputLabel: {
    fontSize: width * 0.04,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: height * 0.0125,
  },
  inputRow: {
    flexDirection: 'row',
    gap: width * 0.025,
    marginBottom: height * 0.025,
  },
  inputBox: {
    width: width * 0.1,
    height: height * 0.0625,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  selectedInputBox: {
    borderColor: '#58CCF7',
    backgroundColor: 'rgba(88, 204, 247, 0.2)',
  },
  inputText: {
    fontSize: width * 0.05,
    fontWeight: 'bold',
    color: '#FFFFFF',
    fontFamily: 'monospace',
  },
  numberPad: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: width * 0.025,
    marginBottom: height * 0.025,
    maxWidth: width * 0.8,
  },
  numberButton: {
    width: width * 0.125,
    height: width * 0.125,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: width * 0.0625,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  numberButtonText: {
    fontSize: width * 0.045,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  actionButtons: {
    flexDirection: 'row',
    gap: width * 0.0375,
    marginBottom: height * 0.025,
  },
  resetButton: {
    backgroundColor: '#E74C3C',
    borderRadius: 20,
    paddingHorizontal: width * 0.05,
    paddingVertical: height * 0.0125,
    shadowColor: '#E74C3C',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  resetButtonText: {
    color: '#FFFFFF',
    fontSize: width * 0.035,
    fontWeight: '600',
  },
  checkButton: {
    backgroundColor: 'rgba(52, 152, 219, 0.6)',
    borderRadius: 20,
    paddingHorizontal: width * 0.05,
    paddingVertical: height * 0.0125,
    shadowColor: '#3498DB',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  checkButtonActive: {
    backgroundColor: '#3498DB',
  },
  checkButtonText: {
    color: '#FFFFFF',
    fontSize: width * 0.035,
    fontWeight: '600',
  },
  continueButton: {
    backgroundColor: '#27AE60',
    borderRadius: 25,
    paddingHorizontal: width * 0.075,
    paddingVertical: height * 0.019,
    shadowColor: '#27AE60',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  continueButtonText: {
    color: '#FFFFFF',
    fontSize: width * 0.04,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
