import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingHorizontal: width * 0.05,
    paddingBottom: height * 0.15,
  },
  progressContainer: {
    alignItems: 'center',
    marginBottom: height * 0.04,
    paddingVertical: height * 0.02,
  },
  progressText: {
    fontSize: width * 0.05,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: height * 0.025,
    textAlign: 'center',
    textShadowColor: 'rgba(88, 204, 247, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
    letterSpacing: 1,
  },
  progressBar: {
    width: width * 0.85,
    height: 12,
    backgroundColor: 'rgba(26, 0, 51, 0.8)',
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(88, 204, 247, 0.5)',
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.6,
        shadowRadius: 8,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  progressFill: {
    height: '100%',
    borderRadius: 20,
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  questionCard: {
    marginVertical: height * 0.03,
    borderRadius: 20,
    padding: width * 0.06,
    borderWidth: 3,
    borderColor: 'rgba(139, 69, 255, 0.8)',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: height * 0.15,
    ...Platform.select({
      ios: {
        shadowColor: '#8B45FF',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.6,
        shadowRadius: 15,
      },
      android: {
        elevation: 15,
      },
    }),
  },
  questionText: {
    fontSize: width * 0.055,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    lineHeight: width * 0.07,
    letterSpacing: 0.5,
    textShadowColor: 'rgba(139, 69, 255, 1)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  answersContainer: {
    marginVertical: height * 0.03,
    gap: height * 0.02,
  },
  answerButton: {
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(139, 69, 255, 0.6)',
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  selectedButton: {
    borderColor: '#FFFFFF',
    borderWidth: 3,
    transform: [{ scale: 1.02 }],
  },
  answerButtonGradient: {
    paddingVertical: height * 0.025,
    paddingHorizontal: width * 0.06,
    alignItems: 'center',
    justifyContent: 'center',
  },
  answerButtonText: {
    fontSize: width * 0.05,
    fontWeight: '800',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    letterSpacing: 1,
  },
  scoreText: {
    fontSize: width * 0.045,
    fontWeight: '600',
    color: '#58CCF7',
    textAlign: 'center',
    marginTop: height * 0.02,
    textShadowColor: 'rgba(88, 204, 247, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 5,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: width * 0.05,
  },
  feedbackModal: {
    width: width * 0.9,
    borderRadius: 25,
    padding: width * 0.06,
    alignItems: 'center',
    borderWidth: 3,
    borderColor: 'rgba(139, 69, 255, 0.8)',
    ...Platform.select({
      ios: {
        shadowColor: '#8B45FF',
        shadowOffset: { width: 0, height: 15 },
        shadowOpacity: 1,
        shadowRadius: 25,
      },
      android: {
        elevation: 20,
      },
    }),
  },
  feedbackTitle: {
    fontSize: width * 0.065,
    fontWeight: '900',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: height * 0.02,
    textShadowColor: 'rgba(139, 69, 255, 1)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 10,
    letterSpacing: 1,
  },
  feedbackMessage: {
    fontSize: width * 0.045,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.95)',
    textAlign: 'center',
    lineHeight: width * 0.065,
    marginBottom: height * 0.03,
    paddingHorizontal: width * 0.02,
  },
  nextButton: {
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(139, 69, 255, 0.6)',
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.6,
        shadowRadius: 10,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  nextButtonGradient: {
    paddingVertical: height * 0.02,
    paddingHorizontal: width * 0.08,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nextButtonText: {
    fontSize: width * 0.05,
    fontWeight: '700',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    letterSpacing: 0.5,
  },
  // Completion overlay
  completionOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: width * 0.05,
  },
  completionCard: {
    width: width * 0.9,
    borderRadius: 30,
    padding: width * 0.08,
    alignItems: 'center',
    borderWidth: 4,
    borderColor: 'rgba(139, 69, 255, 1)',
    ...Platform.select({
      ios: {
        shadowColor: '#8B45FF',
        shadowOffset: { width: 0, height: 20 },
        shadowOpacity: 1,
        shadowRadius: 30,
      },
      android: {
        elevation: 25,
      },
    }),
  },
  completionTitle: {
    fontSize: width * 0.08,
    fontWeight: '900',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: height * 0.02,
    textShadowColor: 'rgba(139, 69, 255, 1)',
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 15,
    letterSpacing: 2,
  },
  completionScore: {
    fontSize: width * 0.06,
    fontWeight: '700',
    color: '#58CCF7',
    textAlign: 'center',
    marginBottom: height * 0.02,
    textShadowColor: 'rgba(88, 204, 247, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  completionMessage: {
    fontSize: width * 0.045,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
    lineHeight: width * 0.065,
    letterSpacing: 0.5,
  },
});
