import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingHorizontal: width * 0.04,
    paddingBottom: height * 0.15,
  },
  title: {
    fontSize: width * 0.065,
    fontWeight: '900',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: height * 0.02,
    textShadowColor: 'rgba(139, 69, 255, 1)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 10,
    letterSpacing: 1,
  },
  instruction: {
    fontSize: width * 0.045,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: height * 0.025,
    lineHeight: width * 0.065,
    paddingHorizontal: width * 0.04,
    textShadowColor: 'rgba(88, 204, 247, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 5,
  },
  hintBox: {
    borderRadius: 15,
    padding: width * 0.04,
    marginBottom: height * 0.03,
    borderWidth: 1,
    borderColor: 'rgba(88, 204, 247, 0.3)',
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  hintText: {
    fontSize: width * 0.04,
    fontWeight: '500',
    color: '#FFFFFF',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  meterContainer: {
    borderRadius: 20,
    padding: width * 0.05,
    marginBottom: height * 0.03,
    borderWidth: 3,
    borderColor: '#8B45FF',
    alignItems: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#8B45FF',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.6,
        shadowRadius: 15,
      },
      android: {
        elevation: 15,
      },
    }),
  },
  meterTitle: {
    fontSize: width * 0.05,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: height * 0.02,
    textShadowColor: 'rgba(139, 69, 255, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
    letterSpacing: 1,
  },
  meterDisplay: {
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    borderRadius: 15,
    padding: width * 0.06,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#00FF00',
    minWidth: width * 0.5,
  },
  meterValue: {
    fontSize: width * 0.08,
    fontWeight: '900',
    color: '#00FF00',
    fontFamily: 'monospace',
    textShadowColor: '#00AA00',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  meterLabel: {
    fontSize: width * 0.035,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.8)',
    marginTop: height * 0.01,
  },
  resultCard: {
    borderRadius: 15,
    padding: width * 0.04,
    marginTop: height * 0.02,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    minWidth: width * 0.6,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  resultTitle: {
    fontSize: width * 0.045,
    fontWeight: '700',
    color: '#1a0033',
    marginBottom: height * 0.008,
  },
  resultPayment: {
    fontSize: width * 0.06,
    fontWeight: '900',
    color: '#1a0033',
    textShadowColor: 'rgba(255, 255, 255, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  resultLabel: {
    fontSize: width * 0.035,
    fontWeight: '500',
    color: 'rgba(26, 0, 51, 0.8)',
    marginTop: height * 0.005,
  },
  optionsTitle: {
    fontSize: width * 0.05,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: height * 0.02,
    textShadowColor: 'rgba(88, 204, 247, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  optionsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: height * 0.03,
    gap: height * 0.015,
  },
  optionCard: {
    width: '48%',
    borderRadius: 15,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(139, 69, 255, 0.4)',
    ...Platform.select({
      ios: {
        shadowColor: '#8B45FF',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  selectedOption: {
    borderColor: '#28A745',
    borderWidth: 3,
    transform: [{ scale: 1.02 }],
  },
  optionGradient: {
    padding: width * 0.04,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: height * 0.12,
  },
  optionKwh: {
    fontSize: width * 0.05,
    fontWeight: '900',
    color: '#1a0033',
    marginBottom: height * 0.005,
  },
  optionCategory: {
    fontSize: width * 0.035,
    fontWeight: '600',
    color: '#1a0033',
    textAlign: 'center',
    marginBottom: height * 0.008,
  },
  optionPayment: {
    fontSize: width * 0.04,
    fontWeight: '700',
    color: '#1a0033',
  },
  educationalNote: {
    borderRadius: 15,
    padding: width * 0.04,
    marginBottom: height * 0.03,
    borderWidth: 1,
    borderColor: 'rgba(139, 69, 255, 0.3)',
    ...Platform.select({
      ios: {
        shadowColor: '#8B45FF',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  noteTitle: {
    fontSize: width * 0.045,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: height * 0.01,
    textShadowColor: 'rgba(139, 69, 255, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  noteText: {
    fontSize: width * 0.04,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.9)',
    lineHeight: width * 0.055,
    textAlign: 'center',
  },
  actionButtons: {
    gap: height * 0.015,
    marginBottom: height * 0.02,
  },
  completeButton: {
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(88, 204, 247, 0.6)',
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.6,
        shadowRadius: 12,
      },
      android: {
        elevation: 10,
      },
    }),
  },
  resetButton: {
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(108, 117, 125, 0.6)',
    ...Platform.select({
      ios: {
        shadowColor: '#6C757D',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  buttonGradient: {
    paddingVertical: height * 0.02,
    paddingHorizontal: width * 0.06,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
  },
  buttonText: {
    fontSize: width * 0.05,
    fontWeight: '800',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    letterSpacing: 0.5,
  },
  linkInfo: {
    borderRadius: 15,
    padding: width * 0.04,
    borderWidth: 1,
    borderColor: 'rgba(40, 167, 69, 0.3)',
    ...Platform.select({
      ios: {
        shadowColor: '#28A745',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  linkTitle: {
    fontSize: width * 0.045,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: height * 0.01,
    textShadowColor: 'rgba(40, 167, 69, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  linkText: {
    fontSize: width * 0.04,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.9)',
    lineHeight: width * 0.055,
    textAlign: 'center',
  },
});
