import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingHorizontal: width * 0.04,
    paddingBottom: height * 0.15,
  },
  title: {
    fontSize: width * 0.065,
    fontWeight: '900',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: height * 0.02,
    textShadowColor: 'rgba(139, 69, 255, 1)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 10,
    letterSpacing: 1,
  },
  instruction: {
    fontSize: width * 0.045,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: height * 0.025,
    lineHeight: width * 0.065,
    paddingHorizontal: width * 0.04,
    textShadowColor: 'rgba(88, 204, 247, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 5,
  },
  progressContainer: {
    alignItems: 'center',
    marginBottom: height * 0.03,
    paddingVertical: height * 0.02,
  },
  progressText: {
    fontSize: width * 0.045,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: height * 0.015,
    textAlign: 'center',
    textShadowColor: 'rgba(88, 204, 247, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
    letterSpacing: 1,
  },
  progressBar: {
    width: width * 0.8,
    height: 10,
    backgroundColor: 'rgba(26, 0, 51, 0.8)',
    borderRadius: 15,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(88, 204, 247, 0.5)',
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.6,
        shadowRadius: 8,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  progressFill: {
    height: '100%',
    borderRadius: 15,
  },
  invoiceContainer: {
    borderRadius: 20,
    padding: width * 0.04,
    marginBottom: height * 0.03,
    borderWidth: 3,
    borderColor: '#8B45FF',
    minHeight: height * 0.35,
    position: 'relative',
    ...Platform.select({
      ios: {
        shadowColor: '#8B45FF',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.6,
        shadowRadius: 15,
      },
      android: {
        elevation: 15,
      },
    }),
  },
  invoiceTitle: {
    fontSize: width * 0.05,
    fontWeight: '900',
    color: '#1a0033',
    textAlign: 'center',
    marginBottom: height * 0.02,
    letterSpacing: 1,
  },
  clickableSection: {
    position: 'absolute',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: 'rgba(139, 69, 255, 0.6)',
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#8B45FF',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 6,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  exploredSection: {
    borderColor: '#28A745',
    borderWidth: 3,
    transform: [{ scale: 1.02 }],
  },
  sectionGradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: width * 0.02,
    borderRadius: 6,
  },
  sectionLabel: {
    fontSize: width * 0.032,
    fontWeight: '700',
    color: '#1a0033',
    textAlign: 'center',
    lineHeight: width * 0.04,
  },
  completeButton: {
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(88, 204, 247, 0.6)',
    marginBottom: height * 0.02,
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.6,
        shadowRadius: 12,
      },
      android: {
        elevation: 10,
      },
    }),
  },
  completeButtonGradient: {
    paddingVertical: height * 0.02,
    paddingHorizontal: width * 0.06,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
  },
  completeButtonText: {
    fontSize: width * 0.05,
    fontWeight: '800',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    letterSpacing: 0.5,
  },
  explanationOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: width * 0.05,
  },
  explanationCard: {
    width: width * 0.9,
    borderRadius: 25,
    padding: width * 0.06,
    alignItems: 'center',
    borderWidth: 3,
    borderColor: 'rgba(139, 69, 255, 0.8)',
    ...Platform.select({
      ios: {
        shadowColor: '#8B45FF',
        shadowOffset: { width: 0, height: 15 },
        shadowOpacity: 1,
        shadowRadius: 25,
      },
      android: {
        elevation: 20,
      },
    }),
  },
  explanationTitle: {
    fontSize: width * 0.06,
    fontWeight: '900',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: height * 0.02,
    textShadowColor: 'rgba(139, 69, 255, 1)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 10,
    letterSpacing: 1,
  },
  explanationText: {
    fontSize: width * 0.045,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.95)',
    textAlign: 'center',
    lineHeight: width * 0.065,
    marginBottom: height * 0.03,
    paddingHorizontal: width * 0.02,
  },
  closeButton: {
    backgroundColor: '#28A745',
    borderRadius: 15,
    paddingVertical: height * 0.015,
    paddingHorizontal: width * 0.06,
    borderWidth: 2,
    borderColor: 'rgba(40, 167, 69, 0.8)',
    ...Platform.select({
      ios: {
        shadowColor: '#28A745',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.6,
        shadowRadius: 8,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  closeButtonText: {
    fontSize: width * 0.045,
    fontWeight: '700',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    letterSpacing: 0.5,
  },
});
