import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingHorizontal: width * 0.04,
    paddingBottom: height * 0.15,
  },
  title: {
    fontSize: width * 0.065,
    fontWeight: '900',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: height * 0.02,
    textShadowColor: 'rgba(139, 69, 255, 1)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 10,
    letterSpacing: 1,
  },
  instruction: {
    fontSize: width * 0.045,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: height * 0.025,
    lineHeight: width * 0.065,
    paddingHorizontal: width * 0.04,
    textShadowColor: 'rgba(88, 204, 247, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 5,
  },
  hintBox: {
    borderRadius: 15,
    padding: width * 0.04,
    marginBottom: height * 0.03,
    borderWidth: 1,
    borderColor: 'rgba(88, 204, 247, 0.3)',
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  hintText: {
    fontSize: width * 0.04,
    fontWeight: '500',
    color: '#FFFFFF',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  itemsContainer: {
    marginBottom: height * 0.03,
    gap: height * 0.015,
  },
  stepCard: {
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  completedCard: {
    borderColor: '#28A745',
    borderWidth: 3,
    transform: [{ scale: 1.02 }],
  },
  stepGradient: {
    padding: width * 0.04,
    minHeight: height * 0.12,
    justifyContent: 'center',
  },
  stepHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: height * 0.01,
  },
  stepIcon: {
    fontSize: width * 0.08,
  },
  stepNumber: {
    fontSize: width * 0.06,
    fontWeight: '900',
    color: '#FFFFFF',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: width * 0.04,
    width: width * 0.08,
    height: width * 0.08,
    textAlign: 'center',
    textAlignVertical: 'center',
    lineHeight: width * 0.08,
  },
  stepTitle: {
    fontSize: width * 0.055,
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: height * 0.008,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    letterSpacing: 1,
  },
  stepDescription: {
    fontSize: width * 0.038,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.95)',
    textAlign: 'center',
    lineHeight: width * 0.055,
    marginBottom: height * 0.015,
    paddingHorizontal: width * 0.02,
  },
  moveButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: width * 0.04,
  },
  moveButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: width * 0.06,
    width: width * 0.12,
    height: width * 0.12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  moveButtonText: {
    fontSize: width * 0.06,
    fontWeight: '900',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  actionButtons: {
    gap: height * 0.015,
    marginBottom: height * 0.02,
  },
  checkButton: {
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(88, 204, 247, 0.6)',
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.6,
        shadowRadius: 12,
      },
      android: {
        elevation: 10,
      },
    }),
  },
  resetButton: {
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(108, 117, 125, 0.6)',
    ...Platform.select({
      ios: {
        shadowColor: '#6C757D',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  buttonGradient: {
    paddingVertical: height * 0.02,
    paddingHorizontal: width * 0.06,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
  },
  buttonText: {
    fontSize: width * 0.05,
    fontWeight: '800',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    letterSpacing: 0.5,
  },
  attemptsText: {
    fontSize: width * 0.04,
    fontWeight: '600',
    color: '#58CCF7',
    textAlign: 'center',
    textShadowColor: 'rgba(88, 204, 247, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 5,
  },
});
