import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
  },
  title: {
    fontSize: width < 400 ? 20 : 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 8,
    paddingHorizontal: 10,
  },
  subtitle: {
    fontSize: width < 400 ? 14 : 16,
    color: '#B8B8B8',
    textAlign: 'center',
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  score: {
    fontSize: width < 400 ? 16 : 18,
    fontWeight: '600',
    color: '#58CCF7',
    textAlign: 'center',
    marginBottom: 20,
    backgroundColor: 'rgba(88, 204, 247, 0.1)',
    borderRadius: 15,
    paddingVertical: 8,
    paddingHorizontal: 16,
    alignSelf: 'center',
  },
  dropZonesContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingHorizontal: 5,
  },
  dropZone: {
    flex: 1,
    marginHorizontal: 5,
    borderRadius: 15,
    borderWidth: 2,
    borderStyle: 'dashed',
    minHeight: height * 0.25,
    padding: 12,
  },
  yesZone: {
    borderColor: '#4CAF50',
    backgroundColor: 'rgba(76, 175, 80, 0.1)',
  },
  noZone: {
    borderColor: '#F44336',
    backgroundColor: 'rgba(244, 67, 54, 0.1)',
  },
  zoneTitle: {
    fontSize: width < 400 ? 14 : 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 10,
  },
  zoneContent: {
    flex: 1,
  },
  placedItem: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 10,
    padding: 8,
    marginBottom: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  placedItemText: {
    fontSize: width < 400 ? 11 : 12,
    color: '#FFFFFF',
    flex: 1,
    marginRight: 8,
  },
  checkMark: {
    fontSize: 16,
    color: '#4CAF50',
    fontWeight: 'bold',
  },
  emptyZoneText: {
    fontSize: width < 400 ? 12 : 14,
    color: '#888888',
    textAlign: 'center',
    marginTop: 20,
    fontStyle: 'italic',
  },
  statementsContainer: {
    maxHeight: height * 0.3,
  },
  statementsTitle: {
    fontSize: width < 400 ? 16 : 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 10,
    textAlign: 'center',
  },
  statementItem: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  selectedStatement: {
    borderColor: '#58CCF7',
    backgroundColor: 'rgba(88, 204, 247, 0.2)',
    transform: [{ scale: 1.02 }],
  },
  statementText: {
    fontSize: width < 400 ? 13 : 14,
    color: '#FFFFFF',
    lineHeight: 20,
  },
  selectedIndicator: {
    marginTop: 8,
    alignItems: 'center',
  },
  selectedIndicatorText: {
    fontSize: 12,
    color: '#58CCF7',
    fontWeight: '600',
  },
  completionMessage: {
    backgroundColor: 'rgba(76, 175, 80, 0.2)',
    borderRadius: 15,
    padding: 16,
    marginTop: 20,
    alignItems: 'center',
  },
  completionText: {
    fontSize: width < 400 ? 18 : 20,
    fontWeight: 'bold',
    color: '#4CAF50',
    textAlign: 'center',
  },
  completionSubText: {
    fontSize: width < 400 ? 14 : 16,
    color: '#FFFFFF',
    textAlign: 'center',
    marginTop: 8,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: width * 0.85,
    maxWidth: 400,
    borderRadius: 20,
    padding: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 20,
  },
  modalTitle: {
    fontSize: width < 400 ? 18 : 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 12,
  },
  modalMessage: {
    fontSize: width < 400 ? 14 : 16,
    color: '#E0E0E0',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 24,
  },
  modalButton: {
    borderRadius: 25,
    overflow: 'hidden',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  modalButtonGradient: {
    paddingVertical: 12,
    paddingHorizontal: 32,
    alignItems: 'center',
    minWidth: 120,
  },
  modalButtonText: {
    fontSize: width < 400 ? 16 : 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
});
